version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  test:
    docker:
      - image: cimg/python:3.8
      - image: mariadb:10.6.7
        environment:
          MARIADB_USER: admin
          MARIADB_PASSWORD: password
          MARIADB_ROOT_PASSWORD: password
          MARIADB_DATABASE: elm_django

    steps:
      - checkout
      - run: pipenv install --dev
      - run: "pipenv run coverage run manage.py test --parallel"
      - run: "pipenv run coverage xml"
      - sonarcloud/scan

workflows:
  cicd:
    jobs:
      - test