version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: pipenv install --dev
      - run: "pipenv run coverage run manage.py test --parallel"
      - run: "pipenv run coverage lcov"
      - sonarcloud/scan

workflows:
  cicd:
    jobs:
      - test