version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: pipenv install --dev
      - run: "pipenv run coverage run manage.py test --parallel"
      - run: "pipenv run coverage lcov"

workflows:
  cicd:
    jobs:
      - test